### ISSUE TITLE
CUDA Out of Memory Error on Colab

### ISSUE THREAD

**Issue by aswathyajith** [kmeng01/rome#10]
I am trying to run the `rome.ipynb` on Google Colab and I'm getting an Out of Memory error on the call to demo_model_editing() function call.

**Comment by kmeng01** [comment]
Hi @aswathyajith, sorry about the inconvenience! I've fixed the problem; please re-pull, and it should work :)

In case you're curious, the OOM is caused by our recent update to the `v*` optimization algorithm, which now requires a bit more memory. My fault for not testing the change on the compute-limited Colab servers!

**Comment by kmeng01** [comment]
Just confirmed that it's working from a fresh run of the notebook — closing for now, but feel free to re-open if anything comes up!

**Comment by aswathyajith** [comment]
Thanks, it works now!
